language: ruby
cache: bundler
rvm:
- 2.1.4
script:
- bundle exec rspec spec/
notifications:
  slack:
    secure: uB4tekEImNQ9Xe+K2MMyzRdqQFAav/xv6UNFw8mPBer4DGtUykb+aYrVIw8DyzAcIHmcWGWWmSSsnFTIKZxelMma89RQ/51Q8JqAEZ0vdGKGO4KnbM7un57AeJMB/lwksiasiFQHtsavKm61a07zYswuJDKDVxKPmfXFP7OEU2U4zV6jGkzpzDWP21mxUEh2xKBUCDK6zKaP6b6m0OwfyNFjhXVDTsu+bUxFcpIdcxCQsggcmPHVzDfzQjC55K+rz28GrAbFZ/yhnCs+8fmEi5gkegL2svSx0RJ6H3KiyKBfjOPqgOsARaPJWQgMoCMy+eXnKF8Pe88+9ypE3JJt790rKr46yeqFz0Y822yndKVkUmWpKgECaTWMEX9HBb7bRdTGWRVcrWkhwsg7dMufqJ/w3bkPwiLOnLgNvmIoBH3RkltxvrCxIkO98ojSTiUh1v+ltc0sfKq7idYJWPlMgkyyC1Vr6FbA2BDG40Mh02UE+/mFxUpHgQ5dpDeCR/OhpsBYzZoDdzFCsGwonIrcLPD2+fFt2ELZq+iRGjF9DBYxEh5fPdLmx/P0Qxjw5QBg7khHRwqK9lm3vaFKj8cVIvT2tpEao5k+YIlmFXbYHNrLhO4eWriokjnLhdn4z77doGrc6zruElkI5oUH0LhxuWi2whKiNYHqx2CAKv1YVY0=
