db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

elasticsearch:
  image: elasticsearch:1.4.4

smtp:
  image: instedd/smtp-debug

sshd:
  image: instedd/cdx-sync-sshd

web:
  build: .
  links:
    - db
    - elasticsearch
    - smtp
    - sshd
  environment:
    RAILS_ENV: production
    MYSQL_HOST: db
    MYSQL_PASSWORD: root
    SMTP_HOST: smtp
    SMTP_PORT: 25
    SMTP_TLS: 'false'
    ELASTICSEARCH_URL: elasticsearch:9200
    SSH_KEYS_PATH: /home/cdx-sync/.ssh/authorized_keys
    SSH_SYNC_DIR: /home/cdx-sync/sync
    POIROT_SERVER: receiver.poirot.dock.er:2120
    SUBSCRIBER_INTERVAL: 1
  ports:
    - 80
  volumes_from:
    - sshd
