db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

elasticsearch:
  image: elasticsearch:1.4.4

smtp:
  image: instedd/smtp-debug

sshd:
  image: instedd/cdx-sync-sshd

web:
  build: .
  links:
    - db
    - elasticsearch
    - smtp
    - sshd
  env_file: docker-dev.env
  ports:
    - 80
  volumes_from:
    - sshd

csv_watch:
  build: .
  command: rake csv:watch
  links:
    - db
    - elasticsearch
    - sshd
  env_file: docker-dev.env
  volumes_from:
    - sshd
