db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

elasticsearch:
  image: elasticsearch:1.4.4

redis:
  image: redis

smtp:
  image: instedd/smtp-debug

sshd:
  image: instedd/cdx-sync-sshd
  environment:
    SYNC_UID: 9999

web:
  build: .
  links:
    - db
    - elasticsearch
    - smtp
    - sshd
    - redis
  env_file: docker-dev.env
  ports:
    - 80:80
  volumes_from:
    - sshd

csv_watch:
  build: .
  command: rake csv:watch
  user: app
  links:
    - db
    - elasticsearch
    - sshd
  env_file: docker-dev.env
  volumes_from:
    - sshd

sidekiq:
  build: .
  command: bundle exec sidekiq
  user: app
  links:
    - db
    - elasticsearch
    - redis
  env_file: docker-dev.env
