db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

elasticsearch:
  image: elasticsearch:1.4.4

redis:
  image: redis

smtp:
  image: instedd/smtp-debug

sshd:
  image: instedd/cdx-sync-sshd

web:
  build: .
  links:
    - db
    - elasticsearch
    - smtp
    - sshd
    - redis
  env_file: docker-dev.env
  ports:
    - 80
  volumes_from:
    - sshd

subscribers:
  build: .
  user: nobody
  links:
    - db
    - elasticsearch
  command: bin/notify_subscribers
  env_file: docker-dev.env

csv_watch:
  build: .
  command: rake csv:watch
  links:
    - db
    - elasticsearch
    - sshd
  env_file: docker-dev.env
  volumes_from:
    - sshd

sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - db
    - elasticsearch
    - redis
  env_file: docker-dev.env
