db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root

elasticsearch:
  image: elasticsearch:1.4.4

smtp:
  image: instedd/smtp-debug

sshd:
  image: instedd/cdx-sync-sshd
  environment:
    SYNC_UID: 9999

web:
  build: .
  links:
    - db
    - elasticsearch
    - smtp
    - sshd
  env_file: docker-dev.env
  ports:
    - 80
  volumes_from:
    - sshd

subscribers:
  build: .
  user: app
  links:
    - db
    - elasticsearch
  command: bin/notify_subscribers
  env_file: docker-dev.env

csv_watch:
  build: .
  user: app
  command: rake csv:watch
  links:
    - db
    - elasticsearch
    - sshd
  env_file: docker-dev.env
  volumes_from:
    - sshd
