# Defaults:

# 1) If a field is not listed here, it can't be used as fiter or group by.
# 2) When listing a date field (eg: created_at):
#   a) The following filters will be enabled: created_at_since and created_at_until
#   b) The following groups will be enabled: year(created_at), month(created_at), day(created_at)
# 3) When listing a string of multi_field type field:
#   a) A 'wildcard' filter with the same name will be enabled.
#   b) A 'flat' group with the same name will be enabled.
# 4) When listing an integer type field:
#   a) A 'match' filter with the same name will be enabled.
#   b) A 'flat' group with the same name will be enabled.
# 5) If the field name ends with '_id', the default group and filter will be created with the name without the '_id': institution_id => institution.
# 6) Range grouping also implies flat grouping, and it will depend on what is received on the request.
# 7) If the default group or filter is not needed, this must be overriden with the keyword 'none'.
# 8) The default field type is 'string'
# 9) If a filter or group has no name, it will be the same as the field name, as specified in (5).
# 10) If a filter or group has no type, it will be the default type as specified in (3) and (4).
# 11) If a filter or group is added with the sole option 'include_default: true', then the default filter or group will be added to the filters or groups array, as specified in (3), (4), and (5).

searchable_fields:
  - name: created_at
    type: date
    filter_parameter_definition:
      - name: since
        type: range
        boundary: from
        options:
          include_lower: true
      - name: until
        type: range
        boundary: to
        options:
          include_lower: true
  - name: event_id
    group_parameter_definition: none
  - name: uuid
    filter_parameter_definition:
      - type: match
    group_parameter_definition: none
  - name: device_uuid
    filter_parameter_definition:
      - name: device
    group_parameter_definition:
      - name: device
  - name: system_user
  - name: device_serial_number
  - name: error_code
    type: integer
  - name: laboratory_id
    type: integer
  - name: institution_id
    type: integer
  - name: parent_locations
    type: integer
    filter_parameter_definition:
      - name: location
    group_parameter_definition:
      - name: admin_level
        type: kind
        reference_table:
          name: locations
          value_field: id
          query_target: admin_level
  - name: age
    type: integer
    filter_parameter_definition:
      - include_default: true
      - name: min_age
        type: range
        boundary: from
        options:
          include_lower: true
      - name: max_age
        type: range
        boundary: to
        options:
          include_upper: true
    group_parameter_definition:
      - type: range
  - name: assay_name
  - name: gender
  - name: ethnicity
  - name: results
    type: nested
    sub_fields:
      - name: result
        type: multi_field
      - name: condition
  - name: test_type
    filter_parameter_definition:
      - type: match
    valid_values:
      options:
        - specimen
        - qc
