common: &default_settings
  server: <%= ENV["POIROT_SERVER"] || "localhost:2120" %>
  enabled: <%= !!ENV["POIROT_SERVER"] %>
  source: cdp
  debug: false

development:
  <<: *default_settings
  mute:
   - /assets/
   - /sidekiq

production:
  <<: *default_settings

test:
  <<: *default_settings
  enabled: false
