common: &default_settings
  server: <%= ENV["POIROT_SERVER"] %>
  stdout: <%= ENV["POIROT_STDOUT"] %>
  suppress_rails_log: <%= ENV["POIROT_SUPPRESS_RAILS_LOG"] %>
  enabled: <%= !!ENV["POIROT_SERVER"] || !!ENV["POIROT_STDOUT"] %>
  debug: false
  source: cdx

development:
  <<: *default_settings
  mute:
   - /assets/
   - /sidekiq

production:
  <<: *default_settings

test:
  <<: *default_settings
  enabled: false
