sensitive_fields:
  - patient_id
  - patient_name
  - patient_telephone_number
  - patient_zip_code

searchable_fields:
  - name: created_at
    type: date
    filter_parameter_definition:
      - name: since
        type: range
        boundary: from
        options:
          include_lower: true
      - name: until
        type: range
        boundary: to
        options:
          include_lower: true
  - name: event_id
    type: string
    filter_parameter_definition:
      - name: event_id
        type: match
  - name: device_uuid
    type: string
    filter_parameter_definition:
      - name: device
        type: match
    group_parameter_definition:
      - name: device
        type: flat
  - name: laboratory_id
    type: integer
    filter_parameter_definition:
      - name: laboratory
        type: match
    group_parameter_definition:
      - name: laboratory
        type: flat
  - name: institution_id
    type: integer
    filter_parameter_definition:
      - name: institution
        type: match
    group_parameter_definition:
      - name: institution
        type: flat
  - name: location_id
    type: integer
    filter_parameter_definition:
  - name: parent_locations
    type: integer
    filter_parameter_definition:
      - name: location
        type: match
    group_parameter_definition:
      - name: admin_level
        type: kind
        reference_table:
          name: locations
          value_field: id
          query_target: depth
  - name: age
    type: integer
    filter_parameter_definition:
      - name: age
        type: match
      - name: min_age
        type: range
        boundary: from
        options:
          include_lower: true
      - name: max_age
        type: range
        boundary: to
        options:
          include_upper: true
    group_parameter_definition:
      - name: age
        type: flat
      - name: age_buckets
        type: range
  - name: assay_name
    type: string
    filter_parameter_definition:
      - name: assay_name
        type: wildcard
  - name: device_serial_number
    type: string
  - name: gender
    type: string
    filter_parameter_definition:
      - name: gender
        type: wildcard
    group_parameter_definition:
      - name: gender
        type: flat
  - name: ethnicity
    type: string
    filter_parameter_definition:
      - name: ethnicity
        type: wildcard
    group_parameter_definition:
      - name: ethnicity
        type: flat
  - name: uuid
    type: string
    filter_parameter_definition:
      - name: uuid
        type: match
  - name: start_time
    type: date
  - name: system_user
    type: string
  - name: results
    type: nested
    sub_fields:
      - name: result
        type: multi_field
        filter_parameter_definition:
          - name: result
            type: wildcard
        group_parameter_definition:
          - name: result
            type: flat
      - name: condition
        type: string
        filter_parameter_definition:
          - name: condition
            type: wildcard
        group_parameter_definition:
          - name: condition
            type: flat
