host: localhost:3000
nndd_url: "/nndd/"
location_service_url: "locations.instedd.org"
location_service_set: 'ne'
sync_pattern: "*.{csv,bef}"
remote_shapefiles:
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm0.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm1.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm2.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm3.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm0.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm1.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm2.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm3.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm0.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm1.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm2.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm3.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm0.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm1.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm2.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/PER_adm3.csv"
