host: localhost:3000
remote_shapefiles:
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm0.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm1.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm2.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm3.json"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm0.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm1.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm2.csv"
  - "http://s3.amazonaws.com/xpert-shapefiles/VNM_adm3.csv"
